2019/09/09 14:02:20 [error] 9266#9266: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET /app/kibana HTTP/2.0", upstream: "http://[::1]:5601/app/kibana", host: "kibana.fd.test", referrer: "https://kibana.fd.test/"
2019/09/09 14:26:27 [error] 9852#9852: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET /ui/fonts/open_sans/open_sans_v13_latin_300.woff2 HTTP/2.0", upstream: "http://[::1]:5601/ui/fonts/open_sans/open_sans_v13_latin_300.woff2", host: "kibana.fd.test", referrer: "https://kibana.fd.test/app/kibana"
2019/09/10 06:04:20 [error] 9852#9852: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET /ui/favicons/favicon.ico HTTP/2.0", upstream: "http://[::1]:5601/ui/favicons/favicon.ico", host: "kibana.fd.test"
2019/09/10 06:24:16 [error] 9852#9852: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET /ui/favicons/favicon.ico HTTP/2.0", upstream: "http://[::1]:5601/ui/favicons/favicon.ico", host: "kibana.fd.test"
2019/09/10 06:26:52 [error] 9852#9852: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET /ui/favicons/favicon.ico HTTP/2.0", upstream: "http://[::1]:5601/ui/favicons/favicon.ico", host: "kibana.fd.test"
2019/09/10 06:28:16 [error] 9852#9852: *51 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET /ui/favicons/favicon.ico HTTP/2.0", upstream: "http://[::1]:5601/ui/favicons/favicon.ico", host: "kibana.fd.test"
2019/09/10 08:45:55 [error] 9852#9852: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET / HTTP/2.0", upstream: "http://[::1]:5601/", host: "kibana.fd.test"
2019/09/10 08:47:10 [error] 9852#9852: *112 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.83.1, server: kibana.fd.test, request: "GET /ui/fonts/open_sans/open_sans_v13_latin_300.woff2 HTTP/2.0", upstream: "http://[::1]:5601/ui/fonts/open_sans/open_sans_v13_latin_300.woff2", host: "kibana.fd.test", referrer: "https://kibana.fd.test/app/kibana"
